version: 0.2

env:
  variables:
    NODE_ENV: production

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm ci

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - aws s3 sync ./build s3://docs.flipbase.com --delete --cache-control "public,max-age=31536000,immutable" --exclude "*.html"
      - aws s3 sync ./build s3://docs.flipbase.com --cache-control "no-cache" --exclude "*" --include "*.html"
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"